### ISSUE TITLE
put_line: parentheses not closed or closed in other put_line

### ISSUE THREAD

**Issue by CoghettoR** [zertovitch/ada-pdf-writer#3]
Hi,

even if not all "pdf" options are implemented, **apdf** is very useful.

Some limitations are _unexpected_: recently, I searched for some time why a part of my page was not displayed: simply I had forgotten to close a parenthesis in a "STRING" expression when writing with "put_line".

Everything is back in order.

However, I can't open a **parenthesis** in a "put_line" entry and close it in another "put_line" entry without getting characters (I'm thinking here of the pdf translation) that are not expected.

I have summarised the situation in the code below:

```ada
-- gnatmake -P pdf_out_gnat.gpr demo.adb
-- ./demo
-- evince demo0?.pdf

with PDF_Out;   use PDF_Out;

procedure demo is
    pdf : PDF_Out_File;
begin

    --- output one two (three) four five
    pdf.Create ("demo01.pdf");
    pdf.Page_Setup (A4_portrait);
    pdf.put_line("one two (three) four five");
    pdf.close;

    --- output empty
    pdf.Create ("demo02.pdf");
    pdf.Page_Setup (A4_portrait);
    pdf.put_line("one two (three four five");
    pdf.close;

    --- output empty
    pdf.Create ("demo03.pdf");
    pdf.Page_Setup (A4_portrait);
    pdf.put_line("one two (three ");
    pdf.put_line("four");
    pdf.put_line("five");
    pdf.close;


    --- output "one two (three ) Tj T* (four) Tj T* (five)"
    pdf.Create ("demo04.pdf");
    pdf.Page_Setup (A4_portrait);
    pdf.put_line("one two (three ");
    pdf.put_line("four");
    pdf.put_line("five)");
    pdf.close;
end demo;
```

**Comment by zertovitch** [comment]
Fixed in 4672967. Thanks for signalling the issue, and sorry for the trouble...
